global: { }

nameOverride: ""
fullnameOverride: ""

lakehouse:
  enabled: true
  fullnameOverride: lakehouse
  defaultBuckets: default

  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4096Mi

  auth:
    rootUser: admin
    rootPassword: password

  extraEnvVars:
    - name: MINIO_LOG_LEVEL
      value: DEBUG

  service:
    type: LoadBalancer
    ports:
      api: 80

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master

  persistence:
    size: 24Gi
    storageClass: lakehouse
    existingClaim: lakehouse-pvc-0
    mountPath: /minio/data

iceberg:
  instances: 1

  catalog:
    warehouse: default
    endpoint: http://lakehouse.io
    access_key: admin
    secret_key: password
    region: ap-southeast-1

warehouse:
  instances: 2

  aws:
    bucketName: ""
    accessKey: ""
    secretKey: ""

opensearch:
  enabled: true

  replicas: 1

  persistence:
    enabled: true
    storageClass: opensearch

  config:
    opensearch.yml: |
      network.host: 0.0.0.0
      cluster.name: opensearch-cluster

  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"
    - name: OPENSEARCH_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: Opensearch_0

  extraInitContainers:
    - name: sysctl
      image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
      imagePullPolicy: "IfNotPresent"
      command:
        - /bin/bash
        - -ec
        - |
          CURRENT=`sysctl -n vm.max_map_count`;
          DESIRED="262144";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w vm.max_map_count=262144;
          fi;
          CURRENT=`sysctl -n fs.file-max`;
          DESIRED="65536";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w fs.file-max=65536;
          fi;
      securityContext:
        runAsUser: 0
        privileged: true
