apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lakehouse
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
{{- range $i, $e := until 2 -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lakehouse-pv-{{ $i }}
spec:
  capacity:
    storage: 16Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: lakehouse
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kube/repows/io/lakehouse/lakehouse-pv-{{ $i }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lakehouse-pvc-{{ $i }}
  namespace: io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  storageClassName: lakehouse
  volumeName: lakehouse-pv-{{ $i }}
---
{{- end -}}
