apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lakehouse
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: lakehouse-api
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: lakehouse
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: minio-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lakehouse
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: lakehouse-console
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: lakehouse
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: minio-console
---
