{{- range .Values.scrapy.euro.spiders -}}
{{- if .enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrape-euro-{{ .name | replace "_" "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scrape-euro
              image: {{ default .image $.Values.scrapy.euro.image }}
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - scrapy crawl {{ .name }} -s ENVIRONMENT=prod
          restartPolicy: Never
---
{{- end -}}
{{- end -}}
