global: { }

nameOverride: ""
fullnameOverride: ""

operator:
  enabled: true
  fullnameOverride: spark-operator

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master

rbac:
  namespaces:
    - name: hub
    - name: pipe
    - name: spark
