global: { }

trino:
  enabled: true
  nameOverride: trino
  # fullnameOverride: trino
  workerNameOverride: trino-worker
  coordinatorNameOverride: trino-coordinator

  server:
    workers: 2

  auth:
    passwordAuth: "admin:password"

  additionalCatalogs:
    opensearch: |
      connector.name=opensearch
      opensearch.host=opensearch.io
      opensearch.port=80
      opensearch.default-schema-name=default

    iceberg: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=http://iceberg.io
      iceberg.rest-catalog.warehouse=s3://iceberg/
      hive.s3.endpoint=http://lakehouse.io
      hive.s3.path-style-access=true
      hive.s3.aws-access-key=admin
      hive.s3.aws-secret-key=password
