apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-pv
spec:
  storageClassName: local
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kube/repows/hub/notebook-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 8Gi
  volumeName: notebook-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-aws
  namespace: {{ .Release.Namespace }}
data:
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.notebook.aws.accessKey }}
    aws_secret_access_key = {{ .Values.notebook.aws.secretKey }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-notebook
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-notebook
  template:
    metadata:
      labels:
        app: hub-notebook
    spec:
      containers:
        - name: notebook
          image: repows.io/notebook-spark
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /home/jovyan/work
              name: notebook
            - mountPath: /home/jovyan/.aws
              name: aws
          ports:
            - containerPort: 8888
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master
      volumes:
        - name: notebook
          persistentVolumeClaim:
            claimName: notebook-pvc
        - name: aws
          configMap:
            name: notebook-aws
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hub-notebook
  type: LoadBalancer
  loadBalancerIP: 192.168.1.88
  ports:
    - port: 80
      targetPort: 8888
---
