---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-postgresql-pv
spec:
  storageClassName: local
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  hostPath:
    path: /kube/repows/dagster/postgresql-pv
  accessModes: [ "ReadWriteOnce" ]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-postgresql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local
  accessModes: [ "ReadWriteOnce" ]
  volumeName: dagster-postgresql-pv
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-rabbitmq-pv
spec:
  storageClassName: local
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  hostPath:
    path: /kube/repows/dagster/rabbitmq-pv
  accessModes: [ "ReadWriteOnce" ]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-rabbitmq-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local
  accessModes: [ "ReadWriteOnce" ]
  volumeName: dagster-rabbitmq-pv
  resources:
    requests:
      storage: 16Gi
---
