apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-driver
rules:
  - apiGroups: [ "" ]
    verbs: [ "*" ]
    resources: [ "pods", "services", "configmaps", "persistentvolumeclaims" ]
---
{{- range .Values.rbac.namespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-driver-{{ .name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .name }}
roleRef:
  kind: ClusterRole
  name: spark-driver
  apiGroup: rbac.authorization.k8s.io
---
{{- end -}}
